server:
  servlet:
    context-path: /demo/api

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/demo_database
    username: demo_user
    password: demo_pass
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true

#hibernate.ddl-auto:
#validate: validar o schema, não faz mudanças no banco de dados.
#update: faz update o schema.
#create: cria o schema, destruindo dados anteriores.
#create-drop: drop o schema quando ao terminar a sessão.